// Generated by Skyramp v1.3.30 on 2026-07-01 17:22:20.276387784 +0000 UTC m=+985.220045485
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_archive_trash_workflow_ui_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/frontend \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_archive_trash_workflow_trace.zip

// Import of required libraries
import { test, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1366000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080");
    await page.waitForLoadState('networkidle');
    // Wait for network activities to finish
    await page.waitForTimeout(6750);

    await page.goto("http://localhost:8080/login");
    await page.waitForLoadState('networkidle');
    // Wait for network activities to finish
    await page.waitForTimeout(3000);


    const playwrightRequest0: Record<string, any> = {
        "email": "testbot-admin@infisical.local",
        "password": "TestbotAdmin@1234!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Secrets Management" }).click();
    await page.getByRole("button", { name: "Create Project" }).waitFor({ state: 'visible', timeout: 10000 });
    await page.getByRole("button", { name: "Create Project" }).click();
    await page.locator("#new-project-name").waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("#new-project-name").fill("Trash UI Test Project");
    const responsePromiseCreateProject = page.waitForResponse("**/api/v2/workspace**");
    await page.getByRole("button", { name: "Create Project" }).click();
    const responseCreateProject = await responsePromiseCreateProject;
    const createdProject = await responseCreateProject.json();
    const projectId = getValue(createdProject, "project.id");
    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Navigate directly to the Development environment's secrets dashboard for this project
    await page.goto(`http://localhost:8080/organizations/25a7abdb-46da-4da7-9d31-38c68e05212a/projects/secret-management/${projectId}/secrets/dev`);
    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(3000);
    await page.getByRole("button", { name: "Add a New Secret" }).first().waitFor({ state: 'visible', timeout: 10000 });

    // Create a secret to archive
    await page.getByRole("button", { name: "Add a New Secret" }).first().click();
    await page.getByRole("textbox", { name: "Type your secret name" }).first().fill("TRASH_UI_TEST_SECRET");
    await page.getByRole("textbox", { name: "secret value" }).first().fill("trash-ui-value");
    await page.getByRole("button", { name: "Create Secret" }).first().click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1000);
    const responsePromiseSave = page.waitForResponse("**/api/v4/secrets/batch**");
    await page.getByRole("button", { name: "Save Changes" }).first().click();
    const responseSave = await responsePromiseSave;

    // Wait for network activities to finish
    await page.waitForTimeout(2000);
    await test.expect(page.getByText("TRASH_UI_TEST_SECRET").first()).toBeVisible();

    // Archive the secret (delete action now archives instead of hard-deleting)
    await page.getByRole("button", { name: "delete-value" }).first().click();
    await page.getByRole("textbox", { name: "Type TRASH_UI_TEST_SECRET here" }).first().fill("TRASH_UI_TEST_SECRET");
    const responsePromiseArchive = page.waitForResponse("**/api/v1/secrets/**/archive**");
    await page.getByRole("button", { name: "Archive Secret" }).first().click();
    const responseArchive = await responsePromiseArchive;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // Reload to bypass any client-side cache and check server-rendered state of the main list
    await page.reload();
    await page.waitForTimeout(3000);
    // Documents IF-SA-C2: an archived secret must NOT appear in the main secrets list.
    await test.expect(page.getByText("TRASH_UI_TEST_SECRET").first()).not.toBeVisible();

    await page.getByRole("button", { name: "Trash" }).first().click();
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    await test.expect(page.getByRole("heading", { name: "Archived Secrets" })).toBeVisible();
    await test.expect(page.getByText("TRASH_UI_TEST_SECRET").first()).toBeVisible();
    await test.expect(page.getByRole("button", { name: "Restore" }).first()).toBeVisible();
    await test.expect(page.getByRole("button", { name: "Delete permanently" }).first()).toBeVisible();

    const responsePromise1 = page.waitForResponse("**/api/v1/secrets/**/restore**");
    await page.getByRole("button", { name: "Restore" }).first().click();
    const response1 = await responsePromise1;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);
    await test.expect(page.getByText("No archived secrets")).toBeVisible();

    await page.getByRole("button", { name: "Trash" }).first().click();
    // Wait for network activities to finish
    await page.waitForTimeout(2000);
    // Documents IF-SA-C4: the restored secret reappears in the main secrets list.
    await test.expect(page.getByText("TRASH_UI_TEST_SECRET").first()).toBeVisible();

    await test.expect(response0.status()).toBe(200);
    await test.expect(responseCreateProject.status()).toBe(200);
    await test.expect(responseSave.status()).toBe(200);
    await test.expect(responseArchive.status()).toBe(200);
    await test.expect(response1.status()).toBe(200);
});
