// Generated by Skyramp v1.3.30 on 2026-06-30 01:47:18.870304074 +0000 UTC m=+671.315158149
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output canonical_projects_tags_lifecycle_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_canonical-projects-tags-lifecycle.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "testbot-tags-removal-test",
        "type": "secret-manager"
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(projectsPostResponse, "project.name"), 'project.name').toBe("testbot-tags-removal-test");
    expect(getValue(projectsPostResponse, "project.id"), 'project.id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Chain project ID from step 1 response
    const projects = getValue(projectsPostResponse, "project.id");

    // Request Body
    const tagsPostRequestBody: string = `{
        "color": "#FF5733",
        "slug": "removal-test-tag"
    }`;

    // Execute Request
    const tagsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{projects}/tags",
        method: "POST",
        body: tagsPostRequestBody,
        headers: headers,
        pathParams: {"projects": projects}
    });

    // Generated Assertions
    expect(tagsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(tagsPostResponse, "tag.slug"), 'tag.slug').toBe("removal-test-tag");
    expect(getValue(tagsPostResponse, "tag.color"), 'tag.color').toBe("#FF5733");
    expect(getValue(tagsPostResponse, "tag.id"), 'tag.id').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Chain tag ID from step 2 response
    const tags = getValue(tagsPostResponse, "tag.id");

    // Execute Request
    const tagsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{projects}/tags",
        method: "GET",
        headers: headers,
        pathParams: {"projects": projects}
    });

    // Generated Assertions
    expect(tagsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(tagsGetResponse, "tags.0.id"), 'tags.0.id').toBe(tags);
    expect(getValue(tagsGetResponse, "tags.1"), 'no second tag').toBeUndefined();

    // Execute Request
    const tagsTagsDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{projects}/tags/{tags}",
        method: "DELETE",
        headers: headers,
        pathParams: {
            "projects": projects,
            "tags": tags
        }
    });

    // Generated Assertions
    expect(tagsTagsDeleteResponse.statusCode, 'status code').toBe(200);
    expect(getValue(tagsTagsDeleteResponse, "tag.id"), 'tag.id').toBe(tags);

    // Execute Request
    const projectsProjectsDeleteResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{projects}",
        method: "DELETE",
        headers: headers,
        pathParams: {"projects": projects}
    });

    // Generated Assertions
    expect(projectsProjectsDeleteResponse.statusCode, 'status code').toBe(204);
});
