// Generated by Skyramp v1.3.30 on 2026-06-30 01:46:55.810554833 +0000 UTC m=+648.255408908
// Command: skyramp generate contract rest http://localhost:8080/api/v1/workspace/{projectId}/tags \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output deprecated_workspace_tags_post_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--path-params projectId=7f3f9c29-5b71-4a0e-b8c2-d94e1f2e3a56 \
// 		--provider \
// 		--request-data {"slug":"test-deprecated-tag","color":"#FF5733"} \
// 		--response-status-code 404 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/workspace/{projectId}/tags POST
test('testTagsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const projectId = "7f3f9c29-5b71-4a0e-b8c2-d94e1f2e3a56";

    // Request Body
    const tagsPostRequestBody: string = `{
        "color": "#FF5733",
        "slug": "test-deprecated-tag"
    }`;

    // Execute Request
    const tagsPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/workspace/{projectId}/tags",
        method: "POST",
        body: tagsPostRequestBody,
        headers: headers,
        pathParams: {"projectId": projectId}
    });

    // Generated Assertions
    expect(tagsPostResponse.statusCode, 'status code').toBe(404);
    expect(getValue(tagsPostResponse, "error"), 'error').toBe("Not Found");
    expect(getValue(tagsPostResponse, "statusCode"), 'body statusCode').toBe(404);
});
