// Generated by Skyramp v1.3.30 on 2026-06-30 01:39:52.003979271 +0000 UTC m=+288.597117661
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_tag_pagination_offset_beyond_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_secret-tag-pagination-offset-beyond.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const workspace = "b2c3d4e5-f6a7-8901-bcde-f01234567890";

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "test-offset-tags-1751293380"
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(projectsPostResponse, "project.name")).toBe("test-offset-tags-1751293380");
    expect(getValue(projectsPostResponse, "project.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Request Body
    const tagsPostRequestBody: string = `{
        "color": "#aabbcc",
        "slug": "single-tag"
    }`;

    // Execute Request
    const tagsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/workspace/{workspace}/tags",
        method: "POST",
        body: tagsPostRequestBody,
        headers: headers,
        pathParams: {"workspace": getValue(projectsPostResponse, "project.id")}
    });

    // Generated Assertions
    expect(tagsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(tagsPostResponse, "workspaceTag.slug")).toBe("single-tag");
    expect(getValue(tagsPostResponse, "workspaceTag.color")).toBe("#aabbcc");
    expect(getValue(tagsPostResponse, "workspaceTag.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Execute Request
    const tagsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{workspace}/tags",
        method: "GET",
        headers: headers,
        pathParams: {"workspace": getValue(projectsPostResponse, "project.id")},
        queryParams: {
            "limit": ["10"],
            "offset": ["999"]
        }
    });

    // Generated Assertions
    expect(tagsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(tagsGetResponse, "tags").length).toBe(0);
    expect(getValue(tagsGetResponse, "totalCount")).toBe(1);
    expect(getValue(tagsGetResponse, "tags.0")).toBeUndefined();
});
