// Generated by Skyramp v1.3.30 on 2026-06-30 01:39:39.45026284 +0000 UTC m=+276.043401240
// Command: skyramp generate contract rest http://localhost:8080/api/v1/workspace/{projectId}/tags \
// 		--api-schema http://localhost:8080/api/docs/json \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output secret_tag_no_auth_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--path-params projectId=c3d4e5f6-a7b8-9012-cdef-012345678901 \
// 		--provider \
// 		--response-status-code 401 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/workspace/{projectId}/tags GET
test('testTagsGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Intentionally no auth header — this test verifies unauthenticated requests return 401
    const headers: Record<string, string> = {};

    // Declaration of variables
    const projectId = "c3d4e5f6-a7b8-9012-cdef-012345678901";

    // Expected Response Body
    const expectedTagsGetResponseBody: string = `{
        "error": "string",
        "message": "string",
        "reqId": "string",
        "statusCode": 0
    }`;

    // Execute Request
    const tagsGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/workspace/{projectId}/tags",
        method: "GET",
        headers: headers,
        pathParams: {"projectId": projectId}
    });

    // Generated Assertions
    expect(tagsGetResponse.statusCode, 'status code').toBe(401);
    expect(getResponseValue(tagsGetResponse, "statusCode")).toBe(401);
    expect(checkSchema(tagsGetResponse, expectedTagsGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(tagsGetResponse, "error"), 'value').not.toBeNull();
    expect(getResponseValue(tagsGetResponse, "message"), 'value').not.toBeNull();
    expect(getResponseValue(tagsGetResponse, "reqId"), 'value').not.toBeNull();
});
