// Generated by Skyramp v1.3.30 on 2026-07-01 17:12:35.259241751 +0000 UTC m=+400.202899472
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_archive_cross_project_idor_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_secret_archive_cross_project_idor.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const raw = "IDOR_VICTIM_SECRET";
    const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

    // Request Body
    const workspacePostRequestBody: string = `{
        "projectName": "idor-victim-proj-20260701"
    }`;

    // Execute Request
    const workspacePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v2/workspace",
        method: "POST",
        body: workspacePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(workspacePostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(workspacePostResponse, "project.id"), 'victim project.id').toMatch(uuidPattern);
    expect(getValue(workspacePostResponse, "project.name"), 'victim project.name').toBe("idor-victim-proj-20260701");
    const victimProjectId = getValue(workspacePostResponse, "project.id");

    // Request Body
    const workspacePost1RequestBody: string = `{
        "projectName": "idor-attacker-proj-20260701"
    }`;

    // Execute Request
    const workspacePost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v2/workspace",
        method: "POST",
        body: workspacePost1RequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(workspacePost1Response.statusCode, 'status code').toBe(200);
    expect(getValue(workspacePost1Response, "project.id"), 'attacker project.id').toMatch(uuidPattern);
    expect(getValue(workspacePost1Response, "project.name"), 'attacker project.name').toBe("idor-attacker-proj-20260701");
    const attackerProjectId = getValue(workspacePost1Response, "project.id");

    // Request Body
    const rawPostRequestBody: string = `{
        "environment": "dev",
        "secretPath": "/",
        "secretValue": "top-secret-value",
        "workspaceId": "${victimProjectId}"
    }`;

    // Execute Request
    const rawPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/secrets/raw/{raw}",
        method: "POST",
        body: rawPostRequestBody,
        headers: headers,
        pathParams: {"raw": raw}
    });

    // Generated Assertions
    expect(rawPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(rawPostResponse, "secret.id"), 'secret.id').toMatch(uuidPattern);
    expect(getValue(rawPostResponse, "secret.secretKey"), 'secret.secretKey').toBe("IDOR_VICTIM_SECRET");
    expect(getValue(rawPostResponse, "secret.workspace"), 'secret.workspace').toBe(victimProjectId);
    const victimSecretId = getValue(rawPostResponse, "secret.id");

    // Request Body
    const archivePostRequestBody: string = `{
        "projectId": "${attackerProjectId}"
    }`;

    // Execute Request — attacker supplies THEIR OWN project (attackerProjectId) while targeting the
    // VICTIM's secret (victimSecretId) which belongs to a different project. This must be rejected.
    const archivePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/secrets/{secretId}/archive",
        method: "POST",
        body: archivePostRequestBody,
        headers: headers,
        pathParams: {"secretId": victimSecretId}
    });

    // Generated Assertions — cross-project archive must be forbidden. This is expected to FAIL
    // against the current implementation, which resolves permission scope from the caller-supplied
    // projectId rather than the secret's actual project, allowing a cross-project bypass.
    expect(archivePostResponse.statusCode, 'status code').toBe(403);
    expect(getValue(archivePostResponse, "error"), 'error').toBe("PermissionDenied");
});
