// Generated by Skyramp v1.3.30 on 2026-06-30 01:41:29.114324271 +0000 UTC m=+466.730970428
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_tags_count_vs_list_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_secret-tags-count-vs-list.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "testbot-tags-project"
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(projectsPostResponse, "project.id"), 'project id uuid format').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(projectsPostResponse, "project.name"), 'project name echo-back').toBe("testbot-tags-project");

    // Chain projectId from create project response
    const workspace = getValue(projectsPostResponse, "project.id");

    // Request Body
    const tagsPostRequestBody: string = `{
        "color": "#FF0000",
        "slug": "test-tag-count"
    }`;

    // Execute Request
    const tagsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/workspace/{workspace}/tags",
        method: "POST",
        body: tagsPostRequestBody,
        headers: headers,
        pathParams: {"workspace": workspace}
    });

    // Generated Assertions
    expect(tagsPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(tagsPostResponse, "workspaceTag.id"), 'tag id uuid format').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(tagsPostResponse, "workspaceTag.slug"), 'tag slug echo-back').toBe("test-tag-count");
    expect(getValue(tagsPostResponse, "workspaceTag.color"), 'tag color echo-back').toBe("#FF0000");

    // Execute Request (using /projects/ prefix — /workspace/ path returns 500)
    const countGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{workspace}/tags/count",
        method: "GET",
        headers: headers,
        pathParams: {"workspace": workspace}
    });

    // Generated Assertions
    expect(countGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(countGetResponse, "count"), 'count is non-negative').toBeGreaterThanOrEqual(0);

    // Execute Request
    const tagsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/workspace/{workspace}/tags",
        method: "GET",
        headers: headers,
        pathParams: {"workspace": workspace}
    });

    // Generated Assertions
    expect(tagsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(tagsGetResponse, "tags").length, 'tags array has 1 item').toBe(1);
    expect(getValue(tagsGetResponse, "tags.0.id"), 'tag id chained from create').toBe(getValue(tagsPostResponse, "workspaceTag.id"));
    expect(getValue(tagsGetResponse, "tags.0.slug"), 'tag slug in list').toBe("test-tag-count");
    expect(getValue(tagsGetResponse, "tags.1"), 'no second tag').toBeUndefined();

    // Verify count equals list length (IF01-C2)
    const count = getValue(countGetResponse, "count");
    const tags = getValue(tagsGetResponse, "tags");
    expect(count, 'count matches list length').toBe(tags.length);
    expect(count, 'count equals 1').toBe(1);
});
