// Generated by Skyramp v1.3.30 on 2026-06-30 01:41:18.326899174 +0000 UTC m=+455.943545331
// Command: skyramp generate contract rest http://localhost:8080/api/v1/workspace/{projectId}/tags/count \
// 		--api-schema http://localhost:8080/api/docs/json \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output secret_tags_count_auth_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--parent-request-data projectId={"projectName": "testbot-contract-tags"} \
// 		--parent-status-code projectId=200 \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/workspace/{projectId}/tags/count GET
test('testCountGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Setup: Create a project to get a valid projectId
    const createProjectRequestBody: string = `{
        "projectName": "testbot-contract-tags"
    }`;
    const createProjectResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/projects",
        method: "POST",
        body: createProjectRequestBody,
        headers: headers
    });
    expect(createProjectResponse.statusCode, 'setup status code').toBe(200);
    expect(getValue(createProjectResponse, "project.id"), 'project id uuid').toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getValue(createProjectResponse, "project.name"), 'project name echo-back').toBe("testbot-contract-tags");
    const projectId = getValue(createProjectResponse, "project.id");

    // Expected Response Body
    const expectedCountGetResponseBody: string = `{
        "count": 0
    }`;

    // Execute Request
    const countGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/projects/{projectId}/tags/count",
        method: "GET",
        headers: headers,
        pathParams: {"projectId": projectId}
    });

    // Generated Assertions
    expect(countGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(countGetResponse, expectedCountGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(countGetResponse, "count"), 'count is zero for new project').toBe(0);
    expect(getResponseValue(countGetResponse, "count"), 'count is non-negative').toBeGreaterThanOrEqual(0);
});
