// Generated by Skyramp v1.3.30 on 2026-06-30 01:39:49.600257881 +0000 UTC m=+286.193396261
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_tag_pagination_limit_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_secret-tag-pagination-limit.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const workspace = "9a3f2e17-5b40-4c88-a1d6-e7f8b9c0d1e2";

    // Request Body
    const projectsPostRequestBody: string = `{
        "projectName": "test-pagination-tags-1751293380"
    }`;

    // Execute Request
    const projectsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects",
        method: "POST",
        body: projectsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(projectsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(projectsPostResponse, "project.name")).toBe("test-pagination-tags-1751293380");
    expect(getResponseValue(projectsPostResponse, "project.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Request Body
    const tagsPostRequestBody: string = `{
        "color": "#ff0000",
        "slug": "alpha-tag"
    }`;

    // Execute Request
    const tagsPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/workspace/{workspace}/tags",
        method: "POST",
        body: tagsPostRequestBody,
        headers: headers,
        pathParams: {"workspace": getResponseValue(projectsPostResponse, "project.id")}
    });

    // Generated Assertions
    expect(tagsPostResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(tagsPostResponse, "workspaceTag.slug")).toBe("alpha-tag");
    expect(getResponseValue(tagsPostResponse, "workspaceTag.color")).toBe("#ff0000");
    expect(getResponseValue(tagsPostResponse, "workspaceTag.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Request Body
    const tagsPost1RequestBody: string = `{
        "color": "#00ff00",
        "slug": "beta-tag"
    }`;

    // Execute Request
    const tagsPost1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/workspace/{workspace}/tags",
        method: "POST",
        body: tagsPost1RequestBody,
        headers: headers,
        pathParams: {"workspace": getResponseValue(projectsPostResponse, "project.id")}
    });

    // Generated Assertions
    expect(tagsPost1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(tagsPost1Response, "workspaceTag.slug")).toBe("beta-tag");
    expect(getResponseValue(tagsPost1Response, "workspaceTag.color")).toBe("#00ff00");
    expect(getResponseValue(tagsPost1Response, "workspaceTag.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);

    // Execute Request
    const tagsGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{workspace}/tags",
        method: "GET",
        headers: headers,
        pathParams: {"workspace": getResponseValue(projectsPostResponse, "project.id")},
        queryParams: {
            "limit": ["1"],
            "offset": ["0"]
        }
    });

    // Generated Assertions
    expect(tagsGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(tagsGetResponse, "tags").length).toBe(1);
    expect(getResponseValue(tagsGetResponse, "totalCount")).toBe(2);
    expect(getResponseValue(tagsGetResponse, "tags.0.id")).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(getResponseValue(tagsGetResponse, "tags.1")).toBeUndefined();
});
