// Generated by Skyramp v1.3.30 on 2026-06-30 01:40:51.81375424 +0000 UTC m=+429.430400417
// Command: skyramp generate contract rest http://localhost:8080/api/v1/workspace/{projectId}/tags/count \
// 		--api-schema http://localhost:8080/api/docs/json \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output secret_tags_count_no_auth_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--path-params projectId=550e8400-e29b-41d4-a716-446655440099 \
// 		--provider \
// 		--response-status-code 401 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/workspace/{projectId}/tags/count GET
test('testCountGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // No authentication header — testing 401 unauthorized response
    const headers: Record<string, string> = {};

    // Declaration of variables
    const projectId = "550e8400-e29b-41d4-a716-446655440099";

    // Expected Response Body
    const expectedCountGetResponseBody: string = `{
        "error": "UnauthorizedError",
        "message": "Token missing",
        "reqId": "req-sQtgjvzHiOgtsh",
        "statusCode": 401
    }`;

    // Execute Request
    const countGetResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/workspace/{projectId}/tags/count",
        method: "GET",
        headers: headers,
        pathParams: {"projectId": projectId}
    });

    // Generated Assertions
    expect(countGetResponse.statusCode, 'status code').toBe(401);
    expect(checkSchema(countGetResponse, expectedCountGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(countGetResponse, "error"), 'error field exact value').toBe("UnauthorizedError");
    expect(getResponseValue(countGetResponse, "statusCode"), 'statusCode field').toBe(401);
    expect(getResponseValue(countGetResponse, "message"), 'message field exact value').toBe("Token missing");
    expect(getResponseValue(countGetResponse, "reqId"), 'reqId format').toMatch(/^req-[a-zA-Z0-9]+$/);
});
