// Generated by Skyramp v1.3.30 on 2026-07-01 17:12:37.18032985 +0000 UTC m=+402.123987562
// Command: skyramp generate integration rest \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_archive_restore_lifecycle_integration_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/infisical/infisical/tests/skyramp/backend/scenario_secret_archive_restore_lifecycle.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const environment = "dev";
    const raw = "LIFECYCLE_TEST_SECRET";
    const secretPath = "/";
    const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    const isoTimestampPattern = /^\d{4}-\d{2}-\d{2}T/;

    // Request Body
    const workspacePostRequestBody: string = `{
        "projectName": "archive-lifecycle-proj-20260701"
    }`;

    // Execute Request
    const workspacePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v2/workspace",
        method: "POST",
        body: workspacePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(workspacePostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(workspacePostResponse, "project.id"), 'project.id').toMatch(uuidPattern);
    expect(getValue(workspacePostResponse, "project.name"), 'project.name').toBe("archive-lifecycle-proj-20260701");
    const workspaceId = getValue(workspacePostResponse, "project.id");

    // Request Body
    const rawRawPostRequestBody: string = `{
        "environment": "dev",
        "secretPath": "/",
        "secretValue": "lifecycle-value",
        "workspaceId": "${workspaceId}"
    }`;

    // Execute Request
    const rawRawPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/secrets/raw/{raw}",
        method: "POST",
        body: rawRawPostRequestBody,
        headers: headers,
        pathParams: {"raw": raw}
    });

    // Generated Assertions
    expect(rawRawPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(rawRawPostResponse, "secret.id"), 'secret.id').toMatch(uuidPattern);
    expect(getValue(rawRawPostResponse, "secret.secretKey"), 'secret.secretKey').toBe("LIFECYCLE_TEST_SECRET");
    expect(getValue(rawRawPostResponse, "secret.workspace"), 'secret.workspace').toBe(workspaceId);
    const secretId = getValue(rawRawPostResponse, "secret.id");

    // Execute Request — baseline: secret must be visible in the main list before archiving
    const rawGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/secrets/raw",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": [environment],
            "secretPath": [secretPath],
            "workspaceId": [workspaceId]
        }
    });

    // Generated Assertions
    expect(rawGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(rawGetResponse, "secrets.0.id"), 'secrets.0.id before archive').toBe(secretId);
    expect(getValue(rawGetResponse, "secrets.0.secretKey"), 'secrets.0.secretKey before archive').toBe("LIFECYCLE_TEST_SECRET");
    expect(getValue(rawGetResponse, "secrets.1"), 'secrets.1 before archive (length 1)').toBeNull();

    // Request Body
    const archivePostRequestBody: string = `{
        "projectId": "${workspaceId}"
    }`;

    // Execute Request — IF-SA-C1: archiving sets archivedAt on the secret
    const archivePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/secrets/{secretId}/archive",
        method: "POST",
        body: archivePostRequestBody,
        headers: headers,
        pathParams: {"secretId": secretId}
    });

    // Generated Assertions
    expect(archivePostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(archivePostResponse, "secret.id"), 'archive secret.id').toBe(secretId);
    expect(getValue(archivePostResponse, "secret.key"), 'archive secret.key').toBe("LIFECYCLE_TEST_SECRET");
    expect(getValue(archivePostResponse, "secret.archivedAt"), 'archive secret.archivedAt').not.toBeNull();
    expect(getValue(archivePostResponse, "secret.archivedAt"), 'archive secret.archivedAt format').toMatch(isoTimestampPattern);

    // Execute Request — IF-SA-C2: archived secret must NOT appear in the main list anymore
    const rawGet1Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/secrets/raw",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": [environment],
            "secretPath": [secretPath],
            "workspaceId": [workspaceId]
        }
    });

    // Generated Assertions
    expect(rawGet1Response.statusCode, 'status code').toBe(200);
    expect(getValue(rawGet1Response, "secrets.0"), 'secrets.0 after archive (length 0)').toBeNull();

    // Execute Request — IF-SA-C3: archived secret must appear in the archived-secrets list
    const archivedGetResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/projects/{projectId}/secrets/archived",
        method: "GET",
        headers: headers,
        pathParams: {"projectId": workspaceId},
        queryParams: {
            "environment": [environment],
            "secretPath": [secretPath]
        }
    });

    // Generated Assertions
    expect(archivedGetResponse.statusCode, 'status code').toBe(200);
    expect(getValue(archivedGetResponse, "secrets.0.id"), 'archived secrets.0.id').toBe(secretId);
    expect(getValue(archivedGetResponse, "secrets.0.key"), 'archived secrets.0.key').toBe("LIFECYCLE_TEST_SECRET");
    expect(getValue(archivedGetResponse, "secrets.0.archivedAt"), 'archived secrets.0.archivedAt').toBe(getValue(archivePostResponse, "secret.archivedAt"));
    expect(getValue(archivedGetResponse, "secrets.1"), 'archived secrets.1').toBeNull();

    // Request Body
    const restorePostRequestBody: string = `{
        "projectId": "${workspaceId}"
    }`;

    // Execute Request — IF-SA-C4: restoring clears archivedAt
    const restorePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v1/secrets/{secretId}/restore",
        method: "POST",
        body: restorePostRequestBody,
        headers: headers,
        pathParams: {"secretId": secretId}
    });

    // Generated Assertions
    expect(restorePostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(restorePostResponse, "secret.id"), 'restore secret.id').toBe(secretId);
    expect(getValue(restorePostResponse, "secret.key"), 'restore secret.key').toBe("LIFECYCLE_TEST_SECRET");
    expect(getValue(restorePostResponse, "secret.archivedAt"), 'restore secret.archivedAt').toBeNull();

    // Execute Request — IF-SA-C4: secret reappears in the main list after restore
    const rawGet2Response = await client.sendRequest({
        url: URL_localhost,
        path: "/api/v3/secrets/raw",
        method: "GET",
        headers: headers,
        queryParams: {
            "environment": [environment],
            "secretPath": [secretPath],
            "workspaceId": [workspaceId]
        }
    });

    // Generated Assertions
    expect(rawGet2Response.statusCode, 'status code').toBe(200);
    expect(getValue(rawGet2Response, "secrets.0.id"), 'secrets.0.id after restore').toBe(secretId);
    expect(getValue(rawGet2Response, "secrets.0.secretKey"), 'secrets.0.secretKey after restore').toBe("LIFECYCLE_TEST_SECRET");
    expect(getValue(rawGet2Response, "secrets.1"), 'secrets.1 after restore (length 1)').toBeNull();
});
