// Generated by Skyramp v1.3.30 on 2026-06-30 01:40:52.238915254 +0000 UTC m=+237.242562950
// Command: skyramp generate contract rest http://localhost:8080/api/v1/webhooks \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output webhook_no_auth_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--request-data {"projectId":"test-project-id","environment":"dev","webhookUrl":"https://example.com/hook"} \
// 		--response-status-code 401 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/webhooks POST
test('testWebhooksPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header - intentionally no auth for this test
    const headers: Record<string, string> = {};

    // Request Body
    const webhooksPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "test-project-id",
        "webhookUrl": "https://example.com/hook"
    }`;

    // Execute Request
    const webhooksPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/webhooks",
        method: "POST",
        body: webhooksPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(webhooksPostResponse.statusCode, 'status code').toBe(401);
    expect(getValue(webhooksPostResponse, 'statusCode'), 'body statusCode').toBe(401);
    expect(getValue(webhooksPostResponse, 'error'), 'error').toBe('UnauthorizedError');
    expect(getValue(webhooksPostResponse, 'message'), 'message').toBe('Token missing');
});
