// Generated by Skyramp v1.3.30 on 2026-06-30 01:40:50.126529469 +0000 UTC m=+235.130177185
// Command: skyramp generate contract rest http://localhost:8080/api/v1/webhooks/{webhookId} \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method PATCH \
// 		--output webhook_patch_http_url_rejection_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--request-data {"webhookUrl":"http://evil.com"} \
// 		--response-status-code 400 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/webhooks/{webhookId} PATCH
test('testWebhooksWebhookIdPatch', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const webhookId = "a1b2c3d4-e5f6-7890-abcd-ef1234567890";

    // Request Body
    const webhooksWebhookIdPatchRequestBody: string = `{
        "webhookUrl": "http://evil.com"
    }`;

    // Execute Request
    const webhooksWebhookIdPatchResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/webhooks/{webhookId}",
        method: "PATCH",
        body: webhooksWebhookIdPatchRequestBody,
        headers: headers,
        pathParams: {"webhookId": webhookId}
    });

    // Generated Assertions
    expect(webhooksWebhookIdPatchResponse.statusCode, 'status code').toBe(422);
    expect(getValue(webhooksWebhookIdPatchResponse, 'statusCode'), 'body statusCode').toBe(422);
    expect(getValue(webhooksWebhookIdPatchResponse, 'error'), 'error').toBe('ValidationFailure');
    expect(getValue(webhooksWebhookIdPatchResponse, 'message.0.message'), 'validation message').toBe('Webhook URL must use HTTPS');
    expect(getValue(webhooksWebhookIdPatchResponse, 'message.0.code'), 'validation code').toBe('custom');
    expect(getValue(webhooksWebhookIdPatchResponse, 'message.0.path.0'), 'field path').toBe('webhookUrl');
});
