// Generated by Skyramp v1.3.30 on 2026-06-30 01:40:46.651928588 +0000 UTC m=+231.655576284
// Command: skyramp generate contract rest http://localhost:8080/api/v1/webhooks \
// 		--auth-type Bearer \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output webhook_http_url_rejection_contract_test.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/tests/skyramp/backend \
// 		--overwrite \
// 		--provider \
// 		--request-data {"projectId":"test-project-id","environment":"dev","webhookUrl":"http://example.com/hook"} \
// 		--response-status-code 400 \
// 		--runtime local

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:8080");

// contract test for /api/v1/webhooks POST
test('testWebhooksPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const webhooksPostRequestBody: string = `{
        "environment": "dev",
        "projectId": "test-project-id",
        "webhookUrl": "http://example.com/hook"
    }`;

    // Execute Request
    const webhooksPostResponse = await client.sendRequest({
        url: URL,
        path: "/api/v1/webhooks",
        method: "POST",
        body: webhooksPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(webhooksPostResponse.statusCode, 'status code').toBe(422);
    expect(getValue(webhooksPostResponse, 'statusCode'), 'body statusCode').toBe(422);
    expect(getValue(webhooksPostResponse, 'error'), 'error').toBe('ValidationFailure');
    expect(getValue(webhooksPostResponse, 'message.0.message'), 'validation message').toBe('Webhook URL must use HTTPS');
    expect(getValue(webhooksPostResponse, 'message.0.code'), 'validation code').toBe('custom');
    expect(getValue(webhooksPostResponse, 'message.0.path.0'), 'field path').toBe('webhookUrl');
});
