// Generated by Skyramp v1.3.32 on 2026-07-02 15:59:01.908465432 +0000 UTC m=+574.924260093
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output secret_archive_restore_flow.spec.ts \
// 		--output-dir /home/runner/work/infisical/infisical/frontend/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/infisical/infisical/.skyramp/secret_archive_restore_flow_trace.zip

// Import of required libraries
import { test, expect, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(571000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const pageErrors: Error[] = [];
    page.on('pageerror', (err) => pageErrors.push(err));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto("http://localhost:8080");
    // Wait for network activities to finish
    await page.waitForTimeout(15000);


    const playwrightRequest0: Record<string, any> = {
        "email": "admin@test.com",
        "password": "Password123!"
    };

    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    await page.locator("#current-password").fill(getValue(playwrightRequest0, "password"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/api/v3/auth/login**");
    await page.getByRole("button", { name: "Continue with Email" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    const secretKey = `TESTBOT_ARCHIVE_KEY_${Date.now()}`;

    await page.goto("http://localhost:8080/organizations/13ce3d37-b745-457c-a53e-cc477d2e7794/projects/secret-management/c8d32c2c-3594-43ce-a055-87e30c20c80c/secrets/dev");
    // Wait for network activities to finish
    await page.waitForTimeout(7951);

    await page.getByRole("button", { name: "Add Secret" }).click();
    await page.getByRole("textbox", { name: "Type your secret name" }).fill(secretKey);
    await page.getByRole("textbox", { name: "secret value" }).fill("testbot-secret-value-123");
    await page.getByRole("button", { name: "Create Secret" }).click();
    // Wait for network activities to finish
    await page.waitForTimeout(12668);

    await page.getByRole("button", { name: "delete-value" }).click();
    await page.getByRole("textbox", { name: `Type ${secretKey} here` }).fill(secretKey);
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise1 = page.waitForResponse("**/api/v1/secrets/**/archive**");
    await page.getByRole("button", { name: "Archive Secret" }).click();
    const response1 = await responsePromise1;
    expect(response1.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("button", { name: "delete-value" })).toHaveCount(0);
    await expect(page.getByText("Add a New Secret")).toBeVisible();

    await page.getByRole("button", { name: "Trash" }).click();
    await expect(page.getByRole("heading", { name: "Archived Secrets" })).toBeVisible();
    await expect(page.getByRole("button", { name: "Restore" })).toHaveCount(1);
    await expect(page.getByText("TESTBOT_ARCHIVE_KEY")).toBeVisible();

    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise2 = page.waitForResponse("**/api/v1/secrets/**/restore**");
    await page.getByRole("button", { name: "Restore" }).click();
    const response2 = await responsePromise2;
    expect(response2.status()).toBe(200);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByText("No archived secrets")).toBeVisible();
    await expect(page.getByRole("button", { name: "Restore" })).toHaveCount(0);

    await page.getByRole("button", { name: "Trash" }).click();
    await expect(page.getByRole("button", { name: "delete-value" })).toHaveCount(1);
    await expect(page.getByText("TESTBOT_ARCHIVE_KEY")).toBeVisible();

    expect(pageErrors).toHaveLength(0);
});
