# Generated by Skyramp v1.3.32 on 2026-07-02 16:01:54.789749167 +0000 UTC m=+747.805543807
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output archived_secret_blocks_recreation_integration_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/backend/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/infisical/infisical/backend/tests/skyramp/scenario_archived_secret_blocks_recreation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    secrets = "ARCHIVE_DUP_1783008049"

    # Request Body
    secrets_POST_request_body = r'''{
        "environment": "dev",
        "projectId": "c8d32c2c-3594-43ce-a055-87e30c20c80c",
        "secretPath": "/",
        "secretValue": "value-before-archive",
        "type": "shared"
    }'''

    # Execute Request
    secrets_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/{secrets}",
        method="POST",
        body=secrets_POST_request_body,
        path_params={"secrets": secrets}
    )

    # Generated Assertions
    assert secrets_POST_response.status_code == 200
    assert skyramp.get_response_value(secrets_POST_response, "secret.secretKey") == "ARCHIVE_DUP_1783008049"
    assert skyramp.get_response_value(secrets_POST_response, "secret.secretValue") == "value-before-archive"
    assert skyramp.get_response_value(secrets_POST_response, "secret.environment") == "dev"
    assert skyramp.get_response_value(secrets_POST_response, "secret.type") == "shared"
    assert skyramp.get_response_value(secrets_POST_response, "secret.version") == 1
    import re
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(secrets_POST_response, "secret.id"), re.IGNORECASE)

    # Request Body
    archive_POST_request_body = r'''{
        "projectId": "c8d32c2c-3594-43ce-a055-87e30c20c80c"
    }'''

    # Execute Request
    secrets_1 = skyramp.get_response_value(secrets_POST_response, "secret.id")
    archive_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/secrets/{secrets}/archive",
        method="POST",
        body=archive_POST_request_body,
        path_params={"secrets": secrets_1}
    )

    # Generated Assertions
    assert archive_POST_response.status_code == 200
    assert skyramp.get_response_value(archive_POST_response, "secret.id") == skyramp.get_response_value(secrets_POST_response, "secret.id")
    assert skyramp.get_response_value(archive_POST_response, "secret.key") == "ARCHIVE_DUP_1783008049"
    assert skyramp.get_response_value(archive_POST_response, "secret.version") == skyramp.get_response_value(secrets_POST_response, "secret.version")
    assert skyramp.get_response_value(archive_POST_response, "secret.archivedAt") is not None

    # Request Body
    secrets_POST_1_request_body = r'''{
        "environment": "dev",
        "projectId": "c8d32c2c-3594-43ce-a055-87e30c20c80c",
        "secretPath": "/",
        "secretValue": "value-after-archive",
        "type": "shared"
    }'''

    # Execute Request
    secrets_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/{secrets}",
        method="POST",
        body=secrets_POST_1_request_body,
        path_params={"secrets": secrets}
    )

    # Generated Assertions
    # Intended behavior: archiving is a soft-delete, so recreating a secret with the same
    # key in the same folder should succeed with a fresh record. This currently FAILS
    # because secretV2BridgeService.createSecret's duplicate check (secretDAL.findOne)
    # does not exclude archivedAt rows, so the archived row still blocks recreation.
    assert secrets_POST_1_response.status_code == 200
    assert skyramp.get_response_value(secrets_POST_1_response, "secret.secretKey") == "ARCHIVE_DUP_1783008049"
    assert skyramp.get_response_value(secrets_POST_1_response, "secret.secretValue") == "value-after-archive"
    assert skyramp.get_response_value(secrets_POST_1_response, "secret.version") == 1
    assert skyramp.get_response_value(secrets_POST_1_response, "secret.id") != skyramp.get_response_value(secrets_POST_response, "secret.id")


if __name__ == "__main__":
    test_integration()
