# Generated by Skyramp v1.3.32 on 2026-07-02 14:23:32.943683859 +0000 UTC m=+157.573254685
# Command: skyramp generate contract rest http://localhost:8080/api/status/ping \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_status_ping_get.py \
# 		--output-dir /home/runner/work/infisical/infisical/backend/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-data {"ping":"pong"} \
# 		--response-status-code 200 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/status/ping GET
def test_ping_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Expected Response Body
    expected_ping_GET_response_body = r'''{
        "ping": "pong"
    }'''

    # Execute Request
    ping_GET_response = client.send_request(
        url=URL,
        path="/api/status/ping",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert ping_GET_response.status_code == 200
    assert skyramp.check_schema(ping_GET_response, expected_ping_GET_response_body)
    assert skyramp.get_response_value(ping_GET_response, "ping") == "pong"


if __name__ == "__main__":
    test_ping_get()
