# Generated by Skyramp v1.3.32 on 2026-07-02 14:23:35.850696997 +0000 UTC m=+160.480267823
# Command: skyramp generate contract rest http://localhost:8080/api/status/ping \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output contract_status_ping_unsupported_method.py \
# 		--output-dir /home/runner/work/infisical/infisical/backend/tests/skyramp \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 404 \
# 		--runtime local \
# 		--skipProvisionParents

# Import of required libraries
import skyramp
import os


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

# contract test for /api/status/ping DELETE
def test_ping_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    ping_DELETE_response = client.send_request(
        url=URL,
        path="/api/status/ping",
        method="DELETE",
        headers=headers
    )

    # Generated Assertions
    assert ping_DELETE_response.status_code == 404
    assert skyramp.get_response_value(ping_DELETE_response, "error") == "Not Found"
    assert skyramp.get_response_value(ping_DELETE_response, "statusCode") == 404
    assert skyramp.get_response_value(ping_DELETE_response, "message") == "Route DELETE:/api/status/ping not found"


if __name__ == "__main__":
    test_ping_delete()
