# Generated by Skyramp v1.3.32 on 2026-07-02 16:02:00.397788235 +0000 UTC m=+753.413582884
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output secret_archive_cross_project_rejected_integration_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/backend/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/infisical/infisical/backend/tests/skyramp/scenario_secret_archive_cross_project_rejected.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "https://localhost")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Declaration of variables
    secrets = "IDOR_TEST_1783008049"

    # Request Body
    secrets_POST_request_body = r'''{
        "environment": "dev",
        "projectId": "c8d32c2c-3594-43ce-a055-87e30c20c80c",
        "secretPath": "/",
        "secretValue": "sensitive-value",
        "type": "shared"
    }'''

    # Execute Request
    secrets_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v4/secrets/{secrets}",
        method="POST",
        body=secrets_POST_request_body,
        path_params={"secrets": secrets}
    )

    # Generated Assertions
    assert secrets_POST_response.status_code == 200
    assert skyramp.get_response_value(secrets_POST_response, "secret.secretKey") == "IDOR_TEST_1783008049"
    assert skyramp.get_response_value(secrets_POST_response, "secret.environment") == "dev"
    import re
    assert re.match(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", skyramp.get_response_value(secrets_POST_response, "secret.id"), re.IGNORECASE)

    # Request Body
    archive_POST_request_body = r'''{
        "projectId": "11111111-2222-4333-8444-555555555555"
    }'''

    # Execute Request
    # Regression guard for the CRITICAL cross-project IDOR fix: archiving a real secret
    # with a projectId that does not own its folder must fail closed with 404, never
    # silently succeed by defaulting the permission subject to "/" + "".
    secrets_1 = skyramp.get_response_value(secrets_POST_response, "secret.id")
    archive_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/v1/secrets/{secrets}/archive",
        method="POST",
        body=archive_POST_request_body,
        path_params={"secrets": secrets_1}
    )

    # Generated Assertions
    assert archive_POST_response.status_code == 404
    assert skyramp.get_response_value(archive_POST_response, "message") == "Secret not found"


if __name__ == "__main__":
    test_integration()
