# Generated by Skyramp v1.3.32 on 2026-07-02 14:23:49.241794842 +0000 UTC m=+173.871365688
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output status_health_check_workflow_integration_test.py \
# 		--output-dir /home/runner/work/infisical/infisical/backend/tests/skyramp \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/infisical/infisical/backend/tests/skyramp/scenario_status_health_check_workflow.json

# Import of required libraries
import skyramp
import os
import re
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:8080")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Execute Request
    status_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/status",
        method="GET"
    )

    # Generated Assertions
    assert status_GET_response.status_code == 200
    assert skyramp.get_response_value(status_GET_response, "message") == "Ok"
    assert re.match(r"^\d{4}-\d{2}-\d{2}T", skyramp.get_response_value(status_GET_response, "date"))

    # Execute Request
    ping_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/status/ping",
        method="GET"
    )

    # Generated Assertions
    assert ping_GET_response.status_code == 200
    assert skyramp.get_response_value(ping_GET_response, "ping") == "pong"


if __name__ == "__main__":
    test_integration()
